run_config:
  agent_name: mouse
  algo_name: dmpo
  task_name: mouse_reach
  run_name:  mouse-forelimb-reach-muscle
  actuator_type: torque
  margin: 0.006

obs_network:
  # observation network params
  use_visual_network: false
  visual_feature_size: 0
  
policy_network_params:
  num_dimensions: 10  # Example value
  tanh_mean: true
  init_scale: 0.1
  fixed_scale: false
  use_tfd_independent: false

learner_network:
  # need to be consistent with the rest of the task if we want to task swichting
  policy_layer_sizes: [512,512,512]
  use_intention: true
  encoder_layer_sizes: [512,512,512]
  decoder_layer_sizes: [512,512,512]
  critic_layer_sizes: [512,512,512]
  intention_size: 3
  use_multi_decoder: false

learner_params:
  # learner parameters
  batch_size: 256
  policy_optimizer_lr: 1e-4
  critic_optimizer_lr: 1e-4
  dual_optimizer_lr: 1e-3
  # checkpoint system
  load_decoder_only: false
  checkpoint_to_load:
  # evaluator params
  eval_average_over: 500
  discount: .99
  # swap_decoder_with_jax: true
  # decoder_h5_path: "/root/vast/eric/track-mjx/track_mjx/ppo_policy_weights.h5"
  # froze_decoder: true 

env_params:
  num_actors: 25
  num_replay_servers: 2
  physics_timestep: 0.001

eval_params:
  eval_average_over: 500